=== datasavvysarah/mongodb-eduhub-project/data/schema-eduhub_db-assignments-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "assignmentId",
    "courseId",
    "dueDate",
    "title"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "assignmentId": {
      "type": "string"
    },
    "courseId": {
      "type": "string"
    },
    "dueDate": {
      "$ref": "#/$defs/Date"
    },
    "title": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== datasavvysarah/mongodb-eduhub-project/data/eduhub_db.assignments.json
[{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc09b"
  },
  "assignmentId": "A001",
  "courseId": "C001",
  "title": "Python Basics Quiz",
  "dueDate": {
    "$date": "2025-10-20T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc09c"
  },
  "assignmentId": "A002",
  "courseId": "C002",
  "title": "Excel Project",
  "dueDate": {
    "$date": "2025-10-25T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc09d"
  },
  "assignmentId": "A003",
  "courseId": "C003",
  "title": "ML Research Task",
  "dueDate": {
    "$date": "2025-10-22T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc09e"
  },
  "assignmentId": "A004",
  "courseId": "C004",
  "title": "Web Page Design",
  "dueDate": {
    "$date": "2025-10-28T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc09f"
  },
  "assignmentId": "A005",
  "courseId": "C005",
  "title": "Advanced Python Project",
  "dueDate": {
    "$date": "2025-10-30T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc0a0"
  },
  "assignmentId": "A006",
  "courseId": "C006",
  "title": "SQL Queries Practice",
  "dueDate": {
    "$date": "2025-10-23T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc0a1"
  },
  "assignmentId": "A007",
  "courseId": "C007",
  "title": "Power BI Dashboard",
  "dueDate": {
    "$date": "2025-10-27T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc0a2"
  },
  "assignmentId": "A008",
  "courseId": "C008",
  "title": "Cloud Research Paper",
  "dueDate": {
    "$date": "2025-10-31T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc0a3"
  },
  "assignmentId": "A009",
  "courseId": "C001",
  "title": "Loops Exercise",
  "dueDate": {
    "$date": "2025-10-24T00:00:00.000Z"
  }
},
{
  "_id": {
    "$oid": "68de0b1126c5d84f47cbc0a4"
  },
  "assignmentId": "A010",
  "courseId": "C002",
  "title": "Data Analysis Report",
  "dueDate": {
    "$date": "2025-10-26T00:00:00.000Z"
  }
}]
